# Generated by Django 5.2.8 on 2025-12-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/originals/')),
                ('gaussian_image', models.ImageField(blank=True, null=True, upload_to='uploads/gaussian/')),
                ('clahe_image', models.ImageField(blank=True, null=True, upload_to='uploads/clahe/')),
                ('threshold_image', models.ImageField(blank=True, null=True, upload_to='uploads/threshold/')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
