# Generated by Django 5.2.8 on 2025-12-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingresult',
            name='median_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/median/'),
        ),
    ]
