# Generated by Django 5.2.8 on 2025-12-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_imageprocessingresult_median_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingresult',
            name='covid_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingresult',
            name='fibrosis_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingresult',
            name='normal_prob',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageprocessingresult',
            name='pneumonia_prob',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
