# Generated by Django 5.2.8 on 2025-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_imageprocessingresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprocessingresult',
            name='check_list',
            field=models.BooleanField(default=False),
        ),
    ]
